language: objective-c

before_install:
- brew update
# Always use the latest xctool version
- brew outdated xctool || brew upgrade xctool

script:
# Just a clean and build of the project on the main scheme
# - xctool clean build -workspace BaseProject.xcworkspace -scheme BaseProject
# Clean and then run the tests
- xctool clean test -workspace BaseProject.xcworkspace -scheme "BaseProject [Test]" -sdk iphonesimulator